resources:
- ad-cart-checkout-currency-email-main-payment-recommendation-shipping_productcat.yaml
patches:
- target:
    kind: HorizontalPodAutoscaler
  patch: |
    $patch: delete
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: dummy
- target:
    kind: Deployment
    name: onlineboutique-ad-ct-co-cur-em-main-pay-re-sh-618477ab-e71b85a2
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-ad-ct-co-cur-em-main-pay-re-sh-618477ab-e71b85a2
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "1710m"
                  memory: "1710Mi"
                requests:
                  cpu: "1710m"
                  memory: "1710Mi"
- target:
    kind: Deployment
    name: onlineboutique-pc-618477ab-0a85caf1
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-pc-618477ab-0a85caf1
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "173m"
                  memory: "173Mi"
                requests:
                  cpu: "173m"
                  memory: "173Mi"
