apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss
  namespace: default
spec:
  action: loss
  mode: one # Aplica a falha em apenas um pod
  selector:
    pods:
      default:
        - onlineboutique-frontend-fe04e9b6-4153050a-5d6775f8c8-kclb5
  loss:
    loss: "100" # Perde 50% dos pacotes
    correlation: "100" # Falha consistente (100% das vezes)
  duration: "2m" # Duração do experimento
