appConfig: weaver.toml
repo: docker.io/camilamedeir0s

listeners:
  - name: boutique
    public: true

groups:
- name: shippingservice
  components:
  - github.com/ServiceWeaver/onlineboutique/shippingservice/ShippingService
- name: recommendationservice
  components:
  - github.com/ServiceWeaver/onlineboutique/recommendationservice/RecommendationService
- name: checkoutservice
  components:
  - github.com/ServiceWeaver/onlineboutique/checkoutservice/CheckoutService
- name: currencyservice
  components:
  - github.com/ServiceWeaver/onlineboutique/currencyservice/CurrencyService
- name: productcatalogservice
  components:
  - github.com/ServiceWeaver/onlineboutique/productcatalogservice/ProductCatalogService