resources:
  - kube_d78a9de1.yaml

patches:
  - target:
      kind: HorizontalPodAutoscaler
    patch: |
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: dummy

  - target:
      kind: Deployment
      name: onlineboutique-front-d78a9de1-5a39da40
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: onlineboutique-front-d78a9de1-5a39da40
      spec:
        template:
          spec:
            containers:
              - name: serviceweaver
                $patch: merge
                resources:
                  limits:
                    cpu: "2360m"
                    memory: "2360Mi"
                  requests:
                    cpu: "2360m"
                    memory: "2360Mi"

  - target:
      kind: Deployment
      name: onlineboutique-services-d78a9de1-aa389eb9
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: onlineboutique-services-d78a9de1-aa389eb9
      spec:
        template:
          spec:
            containers:
              - name: serviceweaver
                $patch: merge
                resources:
                  limits:
                    cpu: "640m"
                    memory: "640Mi"
                  requests:
                    cpu: "640m"
                    memory: "640Mi"
