resources:
- kube_1e4a7c4c.yaml
patches:
- target:
    kind: HorizontalPodAutoscaler
  patch: |
    $patch: delete
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: dummy
- target:
    kind: Deployment
    name: onlineboutique-ad-ct-rec-sh-1e4a7c4c-b7d0c45d
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-ad-ct-rec-sh-1e4a7c4c-b7d0c45d
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "544m"
                  memory: "544Mi"
                requests:
                  cpu: "544m"
                  memory: "544Mi"
- target:
    kind: Deployment
    name: onlineboutique-co-1e4a7c4c-4ff7d17c
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-co-1e4a7c4c-4ff7d17c
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "75m"
                  memory: "75Mi"
                requests:
                  cpu: "75m"
                  memory: "75Mi"
- target:
    kind: Deployment
    name: onlineboutique-cur-1e4a7c4c-f7fa528f
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-cur-1e4a7c4c-f7fa528f
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "173m"
                  memory: "173Mi"
                requests:
                  cpu: "173m"
                  memory: "173Mi"
- target:
    kind: Deployment
    name: onlineboutique-main-em-pay-1e4a7c4c-7765c32c
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-main-em-pay-1e4a7c4c-7765c32c
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "1035m"
                  memory: "1035Mi"
                requests:
                  cpu: "1035m"
                  memory: "1035Mi"
- target:
    kind: Deployment
    name: onlineboutique-pc-1e4a7c4c-3d3317d2
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-pc-1e4a7c4c-3d3317d2
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "173m"
                  memory: "173Mi"
                requests:
                  cpu: "173m"
                  memory: "173Mi"
