resources:
- ad-shipping_cart_checkout_currency_email_main_payment_productcat_recommendation.yaml
patches:
- target:
    kind: HorizontalPodAutoscaler
  patch: |
    $patch: delete
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: dummy
- target:
    kind: Deployment
    name: onlineboutique-ad-sh-b2fd0084-5d2c545a
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-ad-sh-b2fd0084-5d2c545a
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "232m"
                  memory: "232Mi"
                requests:
                  cpu: "232m"
                  memory: "232Mi"
- target:
    kind: Deployment
    name: onlineboutique-co-b2fd0084-c5b9fa68
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-co-b2fd0084-c5b9fa68
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "75m"
                  memory: "75Mi"
                requests:
                  cpu: "75m"
                  memory: "75Mi"
- target:
    kind: Deployment
    name: onlineboutique-ct-b2fd0084-7847907b
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-ct-b2fd0084-7847907b
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "195m"
                  memory: "195Mi"
                requests:
                  cpu: "195m"
                  memory: "195Mi"
- target:
    kind: Deployment
    name: onlineboutique-cur-b2fd0084-2d2f5989
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-cur-b2fd0084-2d2f5989
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "173m"
                  memory: "173Mi"
                requests:
                  cpu: "173m"
                  memory: "173Mi"
- target:
    kind: Deployment
    name: onlineboutique-em-b2fd0084-d54691ae
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-em-b2fd0084-d54691ae
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "50m"
                  memory: "50Mi"
                requests:
                  cpu: "50m"
                  memory: "50Mi"
- target:
    kind: Deployment
    name: onlineboutique-main-b2fd0084-988e4fba
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-main-b2fd0084-988e4fba
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "950m"
                  memory: "950Mi"
                requests:
                  cpu: "950m"
                  memory: "950Mi"
- target:
    kind: Deployment
    name: onlineboutique-pay-b2fd0084-70658b8e
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-pay-b2fd0084-70658b8e
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "35m"
                  memory: "35Mi"
                requests:
                  cpu: "35m"
                  memory: "35Mi"
- target:
    kind: Deployment
    name: onlineboutique-pc-b2fd0084-16b4defb
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-pc-b2fd0084-16b4defb
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "173m"
                  memory: "173Mi"
                requests:
                  cpu: "173m"
                  memory: "173Mi"
- target:
    kind: Deployment
    name: onlineboutique-rec-b2fd0084-73bf0db4
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-rec-b2fd0084-73bf0db4
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "117m"
                  memory: "117Mi"
                requests:
                  cpu: "117m"
                  memory: "117Mi"
