resources:
  - colocated.yaml

patches:
  - target:
      kind: HorizontalPodAutoscaler
    patch: |
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: dummy

  - target:
      kind: Deployment
      name: onlineboutique-colocated-ee0044d1-ff6596e9
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: onlineboutique-colocated-ee0044d1-ff6596e9
      spec:
        template:
          spec:
            containers:
              - name: serviceweaver
                $patch: merge
                resources:
                  limits:
                    cpu: "2000m"
                    memory: "2000Mi"
                  requests:
                    cpu: "2000m"
                    memory: "2000Mi"
