resources:
  - kube_f43e7fba.yaml

patches:
  - target:
      kind: HorizontalPodAutoscaler
    patch: |
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: dummy

  - target:
      kind: Deployment
      name: onlineboutique-front-services-f43e7fba-7c1e32ac
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: onlineboutique-front-services-f43e7fba-7c1e32ac
      spec:
        template:
          spec:
            containers:
              - name: serviceweaver
                $patch: merge
                resources:
                  limits:
                    cpu: "2360m"
                    memory: "2370Mi"
                  requests:
                    cpu: "2360m"
                    memory: "2370Mi"

  - target:
      kind: Deployment
      name: onlineboutique-services-f43e7fba-d8073154
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: onlineboutique-services-f43e7fba-d8073154
      spec:
        template:
          spec:
            containers:
              - name: serviceweaver
                $patch: merge
                resources:
                  limits:
                    cpu: "630m"
                    memory: "630Mi"
                  requests:
                    cpu: "630m"
                    memory: "630Mi"
