resources:
- ad_cart-recommendation_checkout-main_currency_email_payment_productcat_shipping.yaml
patches:
- target:
    kind: HorizontalPodAutoscaler
  patch: |
    $patch: delete
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: dummy
- target:
    kind: Deployment
    name: onlineboutique-ad-e7e5ebe8-aaee8163
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-ad-e7e5ebe8-aaee8163
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "117m"
                  memory: "117Mi"
                requests:
                  cpu: "117m"
                  memory: "117Mi"
- target:
    kind: Deployment
    name: onlineboutique-co-main-e7e5ebe8-e9d34d76
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-co-main-e7e5ebe8-e9d34d76
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "1025m"
                  memory: "1025Mi"
                requests:
                  cpu: "1025m"
                  memory: "1025Mi"
- target:
    kind: Deployment
    name: onlineboutique-ct-rec-e7e5ebe8-3ea3bfee
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-ct-rec-e7e5ebe8-3ea3bfee
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "312m"
                  memory: "312Mi"
                requests:
                  cpu: "312m"
                  memory: "312Mi"
- target:
    kind: Deployment
    name: onlineboutique-cur-e7e5ebe8-7d603ff8
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-cur-e7e5ebe8-7d603ff8
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "173m"
                  memory: "173Mi"
                requests:
                  cpu: "173m"
                  memory: "173Mi"
- target:
    kind: Deployment
    name: onlineboutique-em-e7e5ebe8-61a1e447
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-em-e7e5ebe8-61a1e447
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "50m"
                  memory: "50Mi"
                requests:
                  cpu: "50m"
                  memory: "50Mi"
- target:
    kind: Deployment
    name: onlineboutique-pay-e7e5ebe8-6da81487
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-pay-e7e5ebe8-6da81487
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "35m"
                  memory: "35Mi"
                requests:
                  cpu: "35m"
                  memory: "35Mi"
- target:
    kind: Deployment
    name: onlineboutique-pc-e7e5ebe8-c4653827
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-pc-e7e5ebe8-c4653827
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "173m"
                  memory: "173Mi"
                requests:
                  cpu: "173m"
                  memory: "173Mi"
- target:
    kind: Deployment
    name: onlineboutique-sh-e7e5ebe8-08d0b093
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: onlineboutique-sh-e7e5ebe8-08d0b093
    spec:
      template:
        spec:
          containers:
            - name: serviceweaver
              $patch: merge
              resources:
                limits:
                  cpu: "115m"
                  memory: "115Mi"
                requests:
                  cpu: "115m"
                  memory: "115Mi"
